# --- !Ups

create table PRODUCT (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, NAME TEXT NOT NULL, DESCRIPTION TEXT NOT NULL, PRICE INT NOT NULL, KAT TEXT NOT NULL);
create table USER (ID INT NOT NULL PRIMARY KEY  AUTO_INCREMENT , LOGIN TEXT NOT NULL, PASSWORD TEXT NOT NULL, NAME TEXT NOT NULL , EMAIL TEXT NOT NULL, DATEOFBIRTH TEXT NOT NULL, CITY TEXT NOT NULL );
create table ORDER(ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, ID_USER INT NOT NULL, IDS_PRODUCTS TEXT, TOTAL_PRICE INT NOT NULL, DELIVERY TEXT NOT NULL );
# --- !Downs

DROP TABLE PRODUCT;
DROP TABLE USER;
DROP TABLE ORDER;
